In [1]:
!pip3 install torch torchvision


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 3.5 MB/s  0:00:25 eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 3.2 MB/s  0:00:003.7 MB/s eta 0:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [torchvision] 1/2 [torchvision]


In [2]:
import torch 
import torch.nn as nn

In [20]:
#Input
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [21]:
neuron=nn.Linear(in_features=3, out_features=1)

In [22]:
output=neuron(inputs)

In [23]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [27]:
#verify using formula
# @ is used as a symbol of dot product
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [28]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [29]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)